Develop
mate-academy/py-actor-manager pull request #113
Opened 2022-10-06 11:29 UTC by StasOkhrym

2022-10-06 13:56 UTC, mltdll approved these changes

2022-10-06 13:56 UTC, mltdll commented on app/managers.py
> +    def create(
I don't think it's an issue, but wouldn't this method's definition fit in 79 characters?

2022-10-06 13:56 UTC, mltdll commented on app/managers.py
> +    def update(
Same here.

2022-10-11 17:59 UTC, Nattalli requested changes

2022-10-11 17:59 UTC, Nattalli commented on app/managers.py
> +        )
I think it would be better to add `self._connection.commit()` here too

2022-10-12 15:31 UTC, Nattalli approved these changes
Well done!

2024-06-03 10:56 UTC, closed without merging