solution
mate-academy/py-actor-manager pull request #198
Opened 2022-12-27 23:06 UTC by the-andrew-007

2022-12-28 16:22 UTC, olena-hul commented
Add `main.py` file with methods testing

2022-12-28 16:23 UTC, olena-hul requested changes

2022-12-28 16:23 UTC, olena-hul commented on app/managers.py
> +        literary_formats_cursor = self._connection.execute(
Use the descriptive name for variable. Name it just `cursor` or `actors_cursor`

2022-12-28 16:23 UTC, olena-hul commented on app/managers.py
> +        self._connection = sqlite3.connect(os.path.join("..", "cinema"))
Cinema db can be created in any directory. I think you can just write `sqlite3.connect("cinema")` to make it simple)

2023-01-01 09:23 UTC, Vasyl-Smutok approved these changes

2024-04-21 18:10 UTC, closed without merging