Solution
mate-academy/py-actor-manager pull request #53
Opened 2022-06-16 20:21 UTC by Evgeniy994

2022-06-18 11:09 UTC, darten360 requested changes

2022-06-18 11:09 UTC, darten360 commented on app/managers.py
> +        self._connection.execute(
It's a bad style to use first paranthese near word and second one on a new line

2022-06-18 11:09 UTC, darten360 commented on app/managers.py
> +        actor_cursor = self._connection.execute(
the same

2022-06-18 11:09 UTC, darten360 commented on app/managers.py
> +        self._connection.execute(
I think you understood me

2022-06-19 14:37 UTC, Evgeniy994 commented on app/managers.py
> +        self._connection.execute(
looks like done)

2022-06-20 10:03 UTC, Magus6784 approved these changes

2022-06-21 08:00 UTC, MasterpieceElbow requested changes
Remove unnecessary file `identifier.sqlite` from the pull request

2022-06-21 10:31 UTC, closed without merging