Developer
mate-academy/py-actor-manager pull request #532
Opened 2023-10-16 13:32 UTC by Arsentiy-Blazheiev

2023-10-16 13:37 UTC, Arsentiy-Blazheiev commented
Привіт! Якщо з помилкою ANN201 Missing return type annotation for public function ще більш менш зрозуміло, то як виправити py:26:80: E501 line too long (89 > 79 characters)  у строці 26, я не розумію.

2023-10-17 08:33 UTC, EdAlekseiev commented
> Привіт! Якщо з помилкою ANN201 Missing return type annotation for public function ще більш менш зрозуміло, то як виправити py:26:80: E501 line too long (89 > 79 characters) у строці 26, я не розумію.

Привіт. Тобі потрібно розділити лінію, щоб вона не була занадто великою.
https://stackoverflow.com/questions/53162/how-can-i-do-a-line-break-line-continuation-in-python

2023-10-17 12:29 UTC, YukihiroSM requested changes

2023-10-17 12:29 UTC, YukihiroSM commented on app/main.py
> +    # Actor.objects.delete(1)
remove commented code from file, please.

2023-10-17 12:29 UTC, YukihiroSM commented on app/cinema
This file doesn't have an extension, What is this file?

2023-10-17 12:29 UTC, YukihiroSM commented on app/cinema
If it's non needed - remove from git repo, please. 
https://stackoverflow.com/questions/6313126/how-do-i-remove-a-directory-from-a-git-repository

2023-10-17 15:03 UTC, Arsentiy-Blazheiev commented on app/cinema
Я не зовсім розумію, що потрібно доробити. Закоментований текст був від початку із завданням, для перевірки роботи коду. Я не розкоментовував його, щоб не виконувалися дії, але можу видалити, бо вони працюють. 
Файл cinema це база даних, при створенні я обирав db3, але воно чомусь не відображається в назві як на відео. Що мені змінити?
Та що видаляти з репозиторію?

2023-10-19 17:23 UTC, Arsentiy-Blazheiev commented
Вітаю! 
Підкажіть будь ласка, що я зробив не правильно, і що зробити, щоб завдання було прийнято?

2023-10-30 17:32 UTC, closed without merging