Develop
mate-academy/py-actor-manager pull request #568
Opened 2023-10-31 09:17 UTC by mykolamateichuk

2023-10-31 13:01 UTC, DenPrislipskyi approved these changes

2023-11-02 14:36 UTC, fsocie7y requested changes
pls remove DB from ur PR)

2023-11-02 14:36 UTC, fsocie7y commented on app/managers.py
> +        cursor = self._connection.execute("SELECT * FROM actors")
It's better to follow SQL style guidelines even while writing raw SQL in Python. Therefore I'd suggest to start FROM clause from new line.

2023-11-02 14:36 UTC, fsocie7y commented on app/managers.py
> +            f"DELETE FROM {self.table_name} "
same about from

2023-11-02 16:51 UTC, fsocie7y approved these changes
GJ 👍

2025-10-24 07:21 UTC, closed without merging