solution
mate-academy/py-actor-manager pull request #693
Opened 2024-02-10 21:10 UTC by xborismenx

2024-02-11 11:11 UTC, vasylhnatiuk requested changes

2024-02-11 11:11 UTC, vasylhnatiuk commented on app/managers.py
> +    def all(self) -> list:
```suggestion
    def all(self) -> list[Actor]:
```

2024-02-11 11:11 UTC, vasylhnatiuk commented on app/managers.py
> +    # actor.create("boris", "borisovich")
delete useless comment

2024-02-11 11:11 UTC, vasylhnatiuk commented on app/managers.py
> +    # actor.create("boris", "borisovich")
and useless test code

2024-02-12 19:28 UTC, EdAlekseiev approved these changes
Good job

2026-02-23 07:53 UTC, closed without merging